### PR TITLE
Choose target dependency only for legacy targets.

### PR DESCRIPTION
**Pull request by niklas-arm**
Analog to https://github.com/ARMmbed/mbed-hal-st-stm32f4/pull/34.

This change is dependent on:
- https://github.com/ARMmbed/target-st-nucleo-f401re-gcc/pull/8
- https://github.com/ARMmbed/target-st-stm32f429i-disco/pull/27

@bogdanm @0xc0170 @bremoran @mjs-arm @autopulated

### CODE REVIEW

**Comment by autopulated** [comment]
:+1: after corresponding target updates have been published.

**Comment by bremoran** [comment]
+1 in principle. -1 until builds pass.

**Comment by 0xc0170** [comment]
Jenkins restarted, both targets are green (however jenkins reports here the old status)

@miklis Anything to fix? I restarted the build using SHA.

**Comment by bremoran** [comment]
+1

**Pull request merged**
