### PR TITLE
Combine STM32F429 and STM32F439 CMSIS layers

### PR DESCRIPTION
**Pull request by bremoran**
This change is required by https://github.com/ARMmbed/mbed-hal-st-stm32f4/pull/13

### CODE REVIEW

**Comment by bremoran** [comment]
This PR breaks the C029 layer due to oscillator configuration.  I have a fix coming.

**Comment by bremoran** [comment]
With the referenced PR, this PR now works correctly.

**Comment by bremoran** [comment]
Apparently, I used the wrong keyword.  This PR should now be ready for merge.

**Comment by bremoran** [comment]
cc @bogdanm @0xc0170

**Comment by bogdanm** [comment]
+1

**Comment by 0xc0170** [comment]
+1

**Pull request merged**
