### PR TITLE
Move hal_tick.{c,h} out and stm32f4xx.h in

### PR DESCRIPTION
**Pull request by niklas-arm**
This moves the `hal_tick.{c,h}` into the STM32F4 HAL repository and moves the generic `stm32f4xx.h` header file into here.

The related PRs for this are:
- https://github.com/ARMmbed/mbed-hal-st-stm32f4/pull/26
- https://github.com/ARMmbed/mbed-hal-st-stm32f429zi/pull/19

@bogdanm @0xc0170 @bremoran @autopulated

### CODE REVIEW

**Comment by 0xc0170** [comment]
LGTM

**Comment by niklas-arm** [comment]
Similar to @bremoran comment in https://github.com/ARMmbed/mbed-hal-st-stm32f429zi/pull/19 this also needs an explicit upwards dependency:
```json
"dependencies" : {
    "mbed-hal-stm32f4" : ">=$(published_version)"
}
```

**Comment by 0xc0170** [comment]
;) will do once merged

**Comment by bremoran** [comment]
For reference, the upwards dependency I have specified there is a replacement for ```*``` which has been used in the past.  The point of this is that we want the same benefits as ```*```, but we want to state an explicit minimum version that is required.

**Comment by bremoran** [comment]
This needs to be done before merge, otherwise we're merging code that hasn't had a CI build succeed.

**Comment by 0xc0170** [comment]
f439 targets will be fixed separately soon

**Pull request merged**
