### PR TITLE
Rename F401 dependency to align with F429.

### PR DESCRIPTION
**Pull request by markus-becker-tridonic-com**
We do have a working F401 port of mbedOS, which required the renaming of the cmsis-core-st-stm32f401xe to cmsis-core-stm32f401xe. This aligns the yotta module name with F429, which is released.

The additional modules and targets are
https://github.com/markus-becker-tridonic-com/cmsis-core-stm32f401xe
https://github.com/markus-becker-tridonic-com/mbed-hal-st-stm32f401re
https://github.com/markus-becker-tridonic-com/st-nucleo-f401re-gcc

Would be great if those could be upstreamed as well.

### CODE REVIEW

**Comment by sg-** [comment]
This is a great start but I think there is some confusion about where seperation is between a mcu and board. I think we may need some more documentation on how to do this before accepting this PR.

Specifically see https://github.com/markus-becker-tridonic-com/mbed-hal-st-stm32f401re where board pin names are part of a mcu-hal. This makes modular reuse difficult.

**Comment by 0xc0170** [comment]
A good catch, I'll add here a tree for k64f to show:

```
example-mbedos-blinky 0.0.0
|_ mbed-drivers 0.6.8
| |_ mbed-hal 0.6.2 yotta_modules\mbed-hal
| | |_ mbed-drivers *
| | \_ mbed-hal-freescale 0.5.2 yotta_modules\mbed-hal-freescale
| |   \_ mbed-hal-ksdk-mcu 0.5.4 yotta_modules\mbed-hal-ksdk-mcu
| |     |_ mbed-hal *
| |     |_ uvisor-lib >=0.7.0,<0.8.0
| |     \_ mbed-hal-k64f 0.3.5 yotta_modules\mbed-hal-k64f
| |       |_ mbed-hal *
| |       \_ mbed-hal-frdm-k64f 0.4.3 yotta_modules\mbed-hal-frdm-k64f
| |         \_ mbed-hal >=0.6.0,<0.7.0
```

@sg- we should look again at https://github.com/ARMmbed/mbed-hal/pull/7 (touches also naming as mentioned above by @markus-becker-tridonic-com )

**Comment by markus-becker-tridonic-com** [comment]
We modelled this how F429 in beta is doing it. The alpha of F401 was doing it differently (probably more correctly). Will you change F429? Will you take the F401 from alpha?

**Comment by 0xc0170** [comment]
@markus-becker-tridonic-com PR looks good, although don't change version tag, that one will be updated once merged. We are currently removing cmsis_nvic, there should be soon a new update of cmsis-core to reflect it.

What @sg- pointed out above, it's related to HAL, this is PR regarding cmsis, which seems to be fine.

**Comment by markus-becker-tridonic-com** [comment]
Updated, to resolve the conflict of the version number.

**Comment by markus-becker-tridonic-com** [comment]
@0xc0170 would you merge this updated PR?

**Comment by 0xc0170** [comment]
I don't see this module published in yotta registry (http://yotta.mbed.com/#search/cmsis-core-stm32f401xe) ?

**Comment by markus-becker-tridonic-com** [comment]
The module is mentioned in the first post of this thread. Would be good if the additional modules could be merged into ARMmbed.

**Comment by 0xc0170** [comment]
I am getting this error: error: cmsis-core-stm32f401xe does not exist in the modules registry. Check that the name is correct, and that it has been published.

**Comment by markus-becker-tridonic-com** [comment]
You are right, this module is not there yet. We have created it and would be happy to contribute it as stated in the first comment.

For your reference:
https://github.com/markus-becker-tridonic-com/cmsis-core-stm32f401xe
https://github.com/markus-becker-tridonic-com/mbed-hal-st-stm32f401re
https://github.com/markus-becker-tridonic-com/st-nucleo-f401re-gcc

**Pull request merged**
